version: '3.8'

services:
  visiting-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: visiting-service
    ports:
      - "2525:2525"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres

  postgres:
    image: postgres:16.0
    container_name: visiting-postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: visiting_service
    ports:
      - "5433:5432"
    volumes:
      - visiting_postgres_data:/var/lib/postgresql/data

volumes:
  visiting_postgres_data: